name: sure_safe
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.1.0
  connectivity_plus: ^6.1.1
  multi_select_flutter: ^4.0.0
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.2
  signature: ^5.5.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  geocoding: ^3.0.0
  flutter_local_notifications: ^18.0.1
  restart_app: ^1.3.2
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  syncfusion_flutter_charts: ^28.1.41
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  package_info_plus: ^8.3.0
  syncfusion_flutter_datepicker: ^28.2.4
  pdf: ^3.11.3
  open_filex: ^4.7.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  share_plus: ^11.0.0
  uuid: ^4.5.1
  file_picker: ^10.2.4
  custom_refresh_indicator: ^4.0.1
  webview_flutter: ^4.13.0
  image: ^4.5.4
  flutter_launcher_icons: ^0.14.4
  image_gallery_saver_plus: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  rename: ^3.1.0




flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/json/form.json
    - lib/assets/json/table.json
    - lib/assets/animations_josn/warning.json
    - lib/assets/animations_josn/Loading.json
    - lib/assets/json/modules.json

  
flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen (use a hex color code or color name)
  image: lib/assets/j_kumar_splash.png # Path to the splash image file
  #fill: false Whether to stretch the image to fill the screen
  android: true # Enable splash screen for Android
  ios: true # Enable splash screen for iOS
  android_gravity: center # Aligns the image in the center of the screen
  ios_content_mode: scaleAspectFill # Ensures the image scales proportionally on iOS

  android_12:
    color: "#ffffff"
    image: lib/assets/j_kumar_splash.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo_jkumar_dark_square.png"
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
